const CAL_TINTS=['#f4eee8','#edf2ea','#eaf0f4','#f2ecef','#eef0e7','#f3f0e8','#e9eff0','#f0ece7'];
const escCal=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const calUid=()=>`cal-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
let calState={projects:[],todos:[]},cursor=new Date(),editingCalendarId=null;cursor.setDate(1);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function projectTint(id){const i=(calState.projects||[]).findIndex(p=>p.id===id);return id&&i>=0?CAL_TINTS[i%CAL_TINTS.length]:'#d8d5cd'}
function projectById(id){return(calState.projects||[]).find(p=>p.id===id)}
function repoById(projectId,repoId){return(projectById(projectId)?.subprojects||[]).find(s=>s.id===repoId)}
function calendarItems(){const rows=[];(calState.projects||[]).forEach(p=>(p.subprojects||[]).forEach(s=>(s.tasks||[]).forEach(t=>{if(t.date)rows.push({id:t.id,text:t.text,date:t.date,projectId:p.id,project:p.name,repo:s.name,status:t.status,reminder:!!t.reminder,kind:'task'})})));
  (calState.todos||[]).filter(t=>t.kind==='call'&&t.deadline).forEach(t=>rows.push({id:t.id,text:`CALL · ${t.title}`,date:t.deadline,projectId:t.projectId||'',project:projectById(t.projectId)?.name||'',repo:'',status:t.status||'scout',reminder:true,kind:'call'}));
  (calState.todos||[]).filter(t=>t.kind==='calendar-event'&&t.date).forEach(t=>{const p=projectById(t.projectId),s=repoById(t.projectId,t.repoId);rows.push({id:t.id,text:t.title,date:t.date,time:t.time||'',projectId:t.projectId||'',project:p?.name||'',repo:s?.name||'',status:t.status||'open',reminder:false,kind:t.projectId?'project-event':'event',location:t.location||'',notes:t.notes||''})});
  (calState.todos||[]).filter(t=>!['call','calendar-event'].includes(t.kind)&&!t.sourceTaskId&&t.date).forEach(t=>rows.push({id:t.id,text:t.text,date:t.date,projectId:t.projectId||'',project:projectById(t.projectId)?.name||'',repo:'',status:t.status||'open',reminder:false,kind:'todo'}));return rows}
async function loadCalendar(){try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.ok)calState=await r.json()}catch(e){}if(!Array.isArray(calState.projects))calState.projects=[];if(!Array.isArray(calState.todos))calState.todos=[];renderCalendar()}
async function saveCalendar(){const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(calState)});if(!r.ok)throw new Error('save failed');renderCalendar()}
function renderCalendar(){const y=cursor.getFullYear(),m=cursor.getMonth(),title=document.getElementById('calendarTitle'),grid=document.getElementById('calendarGrid');title.textContent=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(cursor).toUpperCase();const first=new Date(y,m,1),last=new Date(y,m+1,0),lead=(first.getDay()+6)%7,total=Math.ceil((lead+last.getDate())/7)*7,items=calendarItems();let html='';for(let i=0;i<total;i++){const d=new Date(y,m,1-lead+i),key=dateKey(d),inside=d.getMonth()===m,dayItems=items.filter(x=>x.date===key);html+=`<article class="calendar-day ${inside?'':'outside'} ${key===dateKey(new Date())?'today':''}" data-date="${key}"><header><span>${d.getDate()}</span><button class="calendar-day-add" title="Aggiungi evento">+</button></header><div class="calendar-events">${dayItems.map(x=>{const meta=[x.time,x.project,x.repo,x.location].filter(Boolean).join(' · ');return `<div class="calendar-event ${x.status==='done'?'done':''} kind-${x.kind}" data-id="${x.id}" data-kind="${x.kind}" style="--event:${x.kind==='event'?'#111':projectTint(x.projectId)}"><i></i><span><strong>${escCal(x.text)}</strong>${meta?`<small>${escCal(meta)}</small>`:''}</span>${x.reminder?'<b title="Promemoria">◉</b>':''}</div>`}).join('')}</div></article>`}grid.innerHTML=html;grid.querySelectorAll('.calendar-day-add').forEach(b=>b.onclick=e=>{e.stopPropagation();openCalendarEvent(null,b.closest('.calendar-day').dataset.date)});grid.querySelectorAll('.calendar-event').forEach(el=>{if(['event','project-event'].includes(el.dataset.kind))el.onclick=e=>{e.stopPropagation();openCalendarEvent(el.dataset.id)}})}
function fillProjectOptions(selected=''){const sel=document.getElementById('calProject');sel.innerHTML='<option value="">Evento indipendente</option>'+(calState.projects||[]).filter(p=>p.status!=='done').map(p=>`<option value="${p.id}">${escCal(p.name)}</option>`).join('');sel.value=selected||'';fillRepoOptions()}
function fillRepoOptions(selected=''){const projectId=document.getElementById('calProject').value,sel=document.getElementById('calRepo'),repos=projectById(projectId)?.subprojects||[];sel.innerHTML='<option value="">Nessun repo specifico</option>'+repos.filter(s=>s.status!=='done').map(s=>`<option value="${s.id}">${escCal(s.name)}</option>`).join('');sel.value=selected||'';sel.disabled=!projectId}
function openCalendarEvent(id=null,date=''){editingCalendarId=id;const e=id?(calState.todos||[]).find(x=>x.id===id&&x.kind==='calendar-event'):null,item=e||{title:'',date,time:'',projectId:'',repoId:'',location:'',notes:''};document.getElementById('calendarDialogTitle').textContent=id?'Modifica evento':'Nuovo evento';document.getElementById('calTitle').value=item.title||'';document.getElementById('calDate').value=item.date||date||'';document.getElementById('calTime').value=item.time||'';fillProjectOptions(item.projectId||'');fillRepoOptions(item.repoId||'');document.getElementById('calLocation').value=item.location||'';document.getElementById('calNotes').value=item.notes||'';document.getElementById('deleteCalendarEvent').style.visibility=id?'visible':'hidden';document.getElementById('calendarDialog').showModal();setTimeout(()=>document.getElementById('calTitle').focus(),30)}
document.getElementById('newCalendarEvent').onclick=()=>openCalendarEvent();document.getElementById('calProject').onchange=()=>fillRepoOptions();
document.getElementById('saveCalendarEvent').onclick=async()=>{const title=document.getElementById('calTitle').value.trim(),date=document.getElementById('calDate').value;if(!title)return alert('Inserisci il titolo.');if(!date)return alert('Inserisci la data.');const item={id:editingCalendarId||calUid(),kind:'calendar-event',title,date,time:document.getElementById('calTime').value,projectId:document.getElementById('calProject').value,repoId:document.getElementById('calRepo').value,location:document.getElementById('calLocation').value.trim(),notes:document.getElementById('calNotes').value.trim(),status:'open',updatedAt:new Date().toISOString()};const i=calState.todos.findIndex(x=>x.id===item.id);if(i>=0)calState.todos[i]=item;else calState.todos.push(item);document.getElementById('calendarDialog').close();await saveCalendar()};
document.getElementById('deleteCalendarEvent').onclick=async()=>{if(!editingCalendarId||!confirm('Eliminare questo evento?'))return;calState.todos=calState.todos.filter(x=>x.id!==editingCalendarId);document.getElementById('calendarDialog').close();await saveCalendar()};
document.getElementById('prevMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);renderCalendar()};loadCalendar();