const $c=id=>document.getElementById(id);
const escCall=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const callUid=()=>`call-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
let callState={projects:[],todos:[]},editingCallId=null,activeCallFilter='open';
const callRows=()=>Array.isArray(callState.todos)?callState.todos.filter(x=>x.kind==='call'):[];
function daysTo(date){if(!date)return Infinity;const today=new Date();today.setHours(0,0,0,0);const d=new Date(date+'T12:00:00');d.setHours(0,0,0,0);return Math.ceil((d-today)/86400000)}
function statusLabel(v){return({scout:'Da valutare',prepare:'In preparazione',sent:'Inviata',discarded:'Scartata'})[v]||v}
function movementName(id){return(callState.projects||[]).find(p=>p.id===id)?.name||''}
async function loadCalls(){try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.ok)callState=await r.json()}catch(e){}if(!Array.isArray(callState.projects))callState.projects=[];if(!Array.isArray(callState.todos))callState.todos=[];renderCalls()}
async function saveCalls(){const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(callState)});if(!r.ok)throw new Error('save failed');renderCalls()}
function filteredCalls(){let rows=callRows();if(activeCallFilter==='open')rows=rows.filter(x=>!['sent','discarded'].includes(x.status));else if(activeCallFilter!=='all')rows=rows.filter(x=>x.status===activeCallFilter);return rows.sort((a,b)=>(a.deadline||'9999-99-99').localeCompare(b.deadline||'9999-99-99')||a.title.localeCompare(b.title))}
function renderCalls(){const all=callRows(),open=all.filter(x=>!['sent','discarded'].includes(x.status)),next=[...open].filter(x=>x.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline))[0];$c('countScout').textContent=all.filter(x=>x.status==='scout').length;$c('countPrepare').textContent=all.filter(x=>x.status==='prepare').length;$c('countSent').textContent=all.filter(x=>x.status==='sent').length;$c('nextDeadline').textContent=next?new Date(next.deadline+'T12:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short'}):'—';const rows=filteredCalls(),root=$c('callList');$c('callCount').textContent=rows.length;root.innerHTML=rows.length?rows.map(c=>{const days=daysTo(c.deadline),urgent=days>=0&&days<=14,deadline=c.deadline?new Date(c.deadline+'T12:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'}):'NO DEADLINE',movement=movementName(c.projectId);return `<article class="call-card" data-id="${c.id}"><div><span class="call-deadline ${urgent?'urgent':''}">${deadline}</span></div><div class="call-main"><small>${escCall(c.org||'CALL')}${movement?' · '+escCall(movement):''}</small><b>${escCall(c.title)}</b><p>${escCall(c.notes||'')}</p></div><div class="call-actions">${c.url?`<a href="${escCall(c.url)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">CALL ↗</a>`:''}${c.pdf?`<span title="${escCall(c.pdf)}">PDF</span>`:''}<span class="call-status">${statusLabel(c.status)}</span></div></article>`}).join(''):'<div class="empty-calls">Nessuna call in questa vista.</div>';root.querySelectorAll('.call-card').forEach(card=>card.onclick=()=>openCall(card.dataset.id))}
function openCall(id=null){editingCallId=id;const c=id?callRows().find(x=>x.id===id):{id:'',title:'',org:'',status:'scout',deadline:'',url:'',pdf:'',projectId:'',showInCalendar:true,folder:'',notes:''};$c('callDialogTitle').textContent=id?'Modifica call':'Nuova call';$c('callId').value=c.id||'';$c('callTitle').value=c.title||'';$c('callOrg').value=c.org||'';$c('callStatus').value=c.status||'scout';$c('callDeadline').value=c.deadline||'';$c('callUrl').value=c.url||'';$c('callPdf').value=c.pdf||'';$c('callProject').innerHTML='<option value="">Nessuno</option>'+(callState.projects||[]).map(p=>`<option value="${p.id}">${escCall(p.name)}</option>`).join('');$c('callProject').value=c.projectId||'';$c('callCalendar').value=c.showInCalendar===false?'no':'yes';$c('callFolder').value=c.folder||'';$c('callNotes').value=c.notes||'';$c('deleteCallBtn').style.visibility=id?'visible':'hidden';$c('callDialog').showModal();setTimeout(()=>$c('callTitle').focus(),30)}
$c('newCallBtn').onclick=()=>openCall();
$c('saveCallBtn').onclick=async()=>{const title=$c('callTitle').value.trim();if(!title)return alert('Inserisci il titolo della call.');const item={id:editingCallId||callUid(),kind:'call',title,org:$c('callOrg').value.trim(),status:$c('callStatus').value,deadline:$c('callDeadline').value,url:$c('callUrl').value.trim(),pdf:$c('callPdf').value.trim(),projectId:$c('callProject').value,showInCalendar:$c('callCalendar').value==='yes',folder:$c('callFolder').value.trim(),notes:$c('callNotes').value.trim(),updatedAt:new Date().toISOString()};const i=callState.todos.findIndex(x=>x.id===item.id);if(i>=0)callState.todos[i]=item;else callState.todos.push(item);$c('callDialog').close();await saveCalls()};
$c('deleteCallBtn').onclick=async()=>{if(!editingCallId||!confirm('Eliminare questa call?'))return;callState.todos=callState.todos.filter(x=>x.id!==editingCallId);$c('callDialog').close();await saveCalls()};
document.querySelectorAll('.call-filter').forEach(b=>b.onclick=()=>{activeCallFilter=b.dataset.filter;document.querySelectorAll('.call-filter').forEach(x=>x.classList.toggle('active',x===b));renderCalls()});
loadCalls();