// Weekly repo selection + daily task focus. References existing Project -> Repo -> Task data.
const localDateKey=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
function isoWeekKey(){const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return `${x.getUTCFullYear()}-W${String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')}`}
function planning(){if(!state.planning)state.planning={weeks:{},days:{}};state.planning.weeks=state.planning.weeks||{};state.planning.days=state.planning.days||{};return state.planning}
function weekRefs(){return planning().weeks[isoWeekKey()]||[]}
function dayRefs(){return planning().days[localDateKey()]||[]}
function findRepoRef(ref){const p=projectById(ref.projectId),s=(p?.subprojects||[]).find(x=>x.id===ref.repoId);return p&&s?{p,s}:null}
function findTaskRef(ref){const r=findRepoRef(ref),t=(r?.s.tasks||[]).find(x=>x.id===ref.taskId);return r&&t?{...r,t}:null}
function isInWeek(projectId,repoId){return weekRefs().some(r=>r.projectId===projectId&&r.repoId===repoId)}
function planningRender(){if(!state)return;const wk=weekRefs().filter(findRepoRef),dy=dayRefs().filter(findTaskRef);planning().weeks[isoWeekKey()]=wk;planning().days[localDateKey()]=dy;$('weekLabel').textContent=selectedProject==='all'?isoWeekKey():`${projectById(selectedProject)?.name||''} / REPO`;$('todayLabel').textContent=new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date()).toUpperCase();$('weekCount').textContent=selectedProject==='all'?wk.length:(projectById(selectedProject)?.subprojects||[]).length;$('todayCount').textContent=dy.length;renderWeek(wk);renderToday(dy)}
function renderWeek(refs){
  const root=$('weekRepos');
  if(selectedProject!=='all'){
    const p=projectById(selectedProject),repos=(p?.subprojects||[]).filter(s=>s.status!=='done');
    root.innerHTML=repos.length?repos.map(s=>`<article class="week-repo-card project-repo-card ${isInWeek(p.id,s.id)?'in-week':''}" data-project="${p.id}" data-repo="${s.id}"><div><small>${esc(p.name)} ${isInWeek(p.id,s.id)?'· THIS WEEK':''}</small><h3>${esc(s.name)}</h3><span>${(s.tasks||[]).filter(t=>t.status!=='done').length} task aperti</span></div><button class="week-toggle" title="${isInWeek(p.id,s.id)?'Togli dalla settimana':'Aggiungi alla settimana'}">${isInWeek(p.id,s.id)?'✓':'+'}</button></article>`).join(''):'<div class="empty-board">Questo progetto non ha ancora repo attivi.</div>';
    root.querySelectorAll('.project-repo-card').forEach(c=>{c.querySelector('.week-toggle').onclick=async e=>{e.stopPropagation();const exists=isInWeek(c.dataset.project,c.dataset.repo);planning().weeks[isoWeekKey()]=exists?weekRefs().filter(r=>!(r.projectId===c.dataset.project&&r.repoId===c.dataset.repo)):[...weekRefs(),{projectId:c.dataset.project,repoId:c.dataset.repo}];await saveState(false);planningRender()};c.onclick=()=>openRepo(c.dataset.project,c.dataset.repo)});return;
  }
  root.innerHTML=refs.length?refs.map(ref=>{const {p,s}=findRepoRef(ref);return `<article class="week-repo-card" data-project="${p.id}" data-repo="${s.id}"><div><small>${esc(p.name)}</small><h3>${esc(s.name)}</h3><span>${(s.tasks||[]).filter(t=>t.status!=='done').length} task aperti</span></div><button class="week-remove" title="Togli dalla settimana">×</button></article>`}).join(''):'<div class="empty-board">Lunedì scegli qui i repo su cui vuoi lavorare questa settimana.</div>';
  root.querySelectorAll('.week-repo-card').forEach(c=>{c.querySelector('.week-remove').onclick=async e=>{e.stopPropagation();planning().weeks[isoWeekKey()]=weekRefs().filter(r=>!(r.projectId===c.dataset.project&&r.repoId===c.dataset.repo));await saveState(false);planningRender()};c.onclick=()=>openRepo(c.dataset.project,c.dataset.repo)})
}
function renderToday(refs){$('todayTasks').innerHTML=refs.length?refs.map(ref=>{const {p,s,t}=findTaskRef(ref);return `<article class="today-task ${t.status}" data-project="${p.id}" data-repo="${s.id}" data-task="${t.id}"><button class="today-check" title="Segna fatto">${t.status==='done'?'✓':'○'}</button><div><small>${esc(p.name)} / ${esc(s.name)}</small><b>${esc(t.text)}</b></div><button class="today-remove" title="Togli da Today">×</button></article>`}).join(''):'<div class="empty-board">Ogni giorno porta qui i task che vuoi chiudere oggi.</div>';$('todayTasks').querySelectorAll('.today-task').forEach(c=>{c.querySelector('.today-remove').onclick=async()=>{planning().days[localDateKey()]=dayRefs().filter(r=>r.taskId!==c.dataset.task);await saveState(false);planningRender()};c.querySelector('.today-check').onclick=async()=>{const p=projectById(c.dataset.project),s=p.subprojects.find(x=>x.id===c.dataset.repo),t=s.tasks.find(x=>x.id===c.dataset.task);t.status='done';t.completedAt=localDateKey();planning().days[localDateKey()]=dayRefs().filter(r=>r.taskId!==t.id);await saveState();planningRender()}})}
$('addWeekRepo').onclick=()=>{const existing=new Set(weekRefs().map(r=>`${r.projectId}/${r.repoId}`));let repos=repoRecords().filter(r=>r.sub.status==='active'&&!existing.has(`${r.project.id}/${r.sub.id}`));if(selectedProject!=='all')repos=repos.filter(r=>r.project.id===selectedProject);$('weekRepoSelect').innerHTML=repos.map(r=>`<option value="${r.project.id}|${r.sub.id}">${esc(r.project.name)} / ${esc(r.sub.name)}</option>`).join('')||'<option value="">Nessun altro repo attivo</option>';$('weekRepoDialog').showModal()};
$('weekRepoSave').onclick=async()=>{const v=$('weekRepoSelect').value;if(!v)return;const [projectId,repoId]=v.split('|');planning().weeks[isoWeekKey()]=[...weekRefs(),{projectId,repoId}];$('weekRepoDialog').close();await saveState(false);planningRender()};
function refreshTodayTasks(){const [projectId,repoId]=($('todayRepoSelect').value||'|').split('|'),r=findRepoRef({projectId,repoId}),used=new Set(dayRefs().map(x=>x.taskId)),tasks=(r?.s.tasks||[]).filter(t=>t.status!=='done'&&!used.has(t.id));$('todayTaskSuggestions').innerHTML=tasks.map(t=>`<option value="${esc(t.text)}"></option>`).join('')}
$('addTodayTask').onclick=()=>{const refs=weekRefs().filter(findRepoRef);$('todayRepoSelect').innerHTML=refs.map(ref=>{const {p,s}=findRepoRef(ref);return `<option value="${p.id}|${s.id}">${esc(p.name)} / ${esc(s.name)}</option>`}).join('')||'<option value="">Aggiungi prima un repo alla settimana</option>';$('todayTaskInput').value='';refreshTodayTasks();$('todayTaskDialog').showModal();setTimeout(()=>$('todayTaskInput')?.focus(),0)};$('todayRepoSelect').onchange=()=>{$('todayTaskInput').value='';refreshTodayTasks()};
$('todayTaskSave').onclick=async()=>{const [projectId,repoId]=($('todayRepoSelect').value||'|').split('|'),text=$('todayTaskInput').value.trim();if(!projectId||!repoId)return;if(!text)return alert('Scrivi un task.');const r=findRepoRef({projectId,repoId});if(!r)return;const used=new Set(dayRefs().map(x=>x.taskId));let task=(r.s.tasks||[]).find(t=>t.status!=='done'&&!used.has(t.id)&&t.text.trim().toLowerCase()===text.toLowerCase());if(!task){task={id:uid('t'),text,status:'doing',completedAt:''};r.s.tasks.push(task)}else if(task.status==='todo')task.status='doing';planning().days[localDateKey()]=[...dayRefs(),{projectId,repoId,taskId:task.id}];$('todayTaskDialog').close();await saveState(false);planningRender()};
const baseRender=render;render=function(){baseRender();planningRender()};
document.addEventListener('click',e=>{if(e.target.closest('.project-index-card')&&!e.target.closest('.project-edit-pencil'))setTimeout(planningRender,0);if(e.target.closest('.category-dot'))setTimeout(planningRender,0)});
setTimeout(planningRender,100);