// Home workspace: Movement -> Repository -> Task/To do.
// There is one source of truth: repository tasks. Home simply creates and visualizes those tasks.
const workspaceToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const hoursValue=v=>Math.max(0,Number(String(v??'').replace(',','.'))||0);
function isoWeekKey(date=new Date()){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return `${d.getUTCFullYear()}-W${String(Math.ceil((((d-y)/86400000)+1)/7)).padStart(2,'0')}`}
function weekFromDate(value){if(!value)return'';const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?'':isoWeekKey(d)}
function mondayFromWeek(week){if(!/^\d{4}-W\d{2}$/.test(week||''))return'';const [year,w]=week.split('-W').map(Number),jan4=new Date(Date.UTC(year,0,4)),jan4Day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-(jan4Day-1)+(w-1)*7);return `${monday.getUTCFullYear()}-${String(monday.getUTCMonth()+1).padStart(2,'0')}-${String(monday.getUTCDate()).padStart(2,'0')}`}
const currentWeek=()=>isoWeekKey(new Date());
function migrateTaskWeeks(){(state.projects||[]).forEach(p=>(p.subprojects||[]).forEach(s=>(s.tasks||[]).forEach(t=>{if(t.week===undefined)t.week=weekFromDate(t.date||'');if(t.week&&!t.date)t.date=mondayFromWeek(t.week);t.hours=hoursValue(t.hours);t.notes=t.notes||'';t.reminder=!!t.reminder})));if(!state.todosMergedIntoTasksV2){(state.todos||[]).filter(t=>t.status!=='done'&&t.repoId).forEach(t=>{const r=repoByIds(t.projectId,t.repoId);if(!r)return;if(!(r.s.tasks||[]).some(x=>x.text===t.text&&x.status!=='done')){const week=t.week||weekFromDate(t.date)||currentWeek();r.s.tasks.push({id:uid('t'),text:t.text,status:'todo',week,date:mondayFromWeek(week),hours:hoursValue(t.hours),notes:'',reminder:false,completedAt:''})}});state.todosMergedIntoTasksV2=true}}
function repoByIds(projectId,repoId){const p=projectById(projectId),s=(p?.subprojects||[]).find(x=>x.id===repoId);return p&&s?{p,s}:null}
function visibleRepos(){let rows=repoRecords().filter(r=>r.sub.status!=='done');if(selectedProject!=='all')rows=rows.filter(r=>r.project.id===selectedProject);return rows}
function projectTint(projectId){const i=(state.projects||[]).findIndex(p=>p.id===projectId);return i<0?'#d8d5cd':PROJECT_TINTS[i%PROJECT_TINTS.length]}
function allOpenTasks(){const rows=[];(state.projects||[]).forEach(p=>(p.subprojects||[]).forEach(s=>(s.tasks||[]).forEach(t=>{if(t.status!=='done')rows.push({id:t.id,text:t.text,status:t.status,week:t.week||'',hours:hoursValue(t.hours),projectId:p.id,repoId:s.id,project:p,repo:s,task:t})})));const now=currentWeek();return rows.sort((a,b)=>{const ac=a.week===now?0:1,bc=b.week===now?0:1;if(ac!==bc)return ac-bc;if(!a.week&&b.week)return 1;if(a.week&&!b.week)return-1;return(a.week||'9999').localeCompare(b.week||'9999')||a.text.localeCompare(b.text)})}
function workspaceRender(){if(!state)return;migrateTaskWeeks();renderWorkspaceRepos();renderTodoComposer();renderTodos()}
function renderWorkspaceRepos(){const rows=visibleRepos(),root=$('workspaceRepos');if(!root)return;$('visibleRepoCount').textContent=rows.length;$('repoScopeLabel').textContent=selectedProject==='all'?'REPOSITORIES':`${projectById(selectedProject)?.name||''} / REPOSITORIES`;root.innerHTML=rows.length?rows.map(({project:p,sub:s})=>{const tasks=(s.tasks||[]).filter(t=>t.status!=='done');return `<article class="workspace-repo-card" data-project="${p.id}" data-repo="${s.id}" style="--repo-tint:${projectTint(p.id)}"><button type="button" class="workspace-repo-edit" title="Modifica repo">✎</button><small>${CATEGORY_LABELS[p.category]} / ${esc(p.name)}</small><h3>${esc(s.name)}</h3><div class="repo-todo-preview">${tasks.length?tasks.map(t=>`<div class="repo-todo-row ${t.status}"><i></i><span>${esc(t.text)}</span>${t.week?`<time>${esc(t.week.replace('-W',' · W'))}</time>`:''}</div>`).join(''):'<span class="empty-inline">Nessun task aperto</span>'}</div></article>`}).join(''):'<div class="empty-board">Nessun repository in questa selezione.</div>';root.querySelectorAll('.workspace-repo-card').forEach(card=>{card.onclick=e=>{if(e.target.closest('.workspace-repo-edit'))return;openRepo(card.dataset.project,card.dataset.repo)};card.querySelector('.workspace-repo-edit').onclick=e=>{e.stopPropagation();openRepoEditor(card.dataset.project,card.dataset.repo)}})}
function renderTodoComposer(){const select=$('todoRepo');if(!select)return;let rows=repoRecords().filter(r=>r.sub.status!=='done'&&r.project.status!=='done');if(selectedProject!=='all')rows=rows.sort((a,b)=>(a.project.id===selectedProject?-1:0)-(b.project.id===selectedProject?-1:0));select.innerHTML='<option value="">Scegli repo…</option>'+rows.map(r=>`<option value="${r.project.id}|${r.sub.id}">${esc(r.project.name)} / ${esc(r.sub.name)}</option>`).join('');if(selectedProject!=='all'){const first=rows.find(r=>r.project.id===selectedProject);if(first)select.value=`${first.project.id}|${first.sub.id}`}}
function renderTodos(){const root=$('todoList');if(!root)return;const rows=allOpenTasks(),now=currentWeek();$('todoCount').textContent=rows.length;const weekHours=rows.filter(r=>r.week===now).reduce((a,r)=>a+r.hours,0);if($('todoHours'))$('todoHours').textContent=weekHours?`${String(weekHours).replace('.',',')} h`:'';root.innerHTML=rows.length?rows.map(r=>{const active=r.week===now,slot=r.week?(active?'THIS WEEK':r.week.replace('-W',' · W')):'NON PROGRAMMATA';return `<article class="free-todo ${active?'is-this-week':'is-other-week'}" data-id="${r.id}" data-project="${r.projectId}" data-repo="${r.repoId}"><button class="free-todo-check" title="Completa">○</button><i class="movement-signal" style="--signal:${projectTint(r.projectId)}"></i><div class="free-todo-copy"><span>${esc(r.text)}</span><small>${esc(r.project.name)} / ${esc(r.repo.name)} · ${esc(slot)}</small></div></article>`}).join(''):'<div class="empty-board">Nessuna to do aperta.</div>';root.querySelectorAll('.free-todo').forEach(row=>{row.querySelector('.free-todo-check').onclick=async()=>{const r=repoByIds(row.dataset.project,row.dataset.repo),t=(r?.s.tasks||[]).find(x=>x.id===row.dataset.id);if(t){t.status='done';t.completedAt=workspaceToday()}await saveState(false);workspaceRender()}})}
$('todoComposer').onsubmit=async e=>{e.preventDefault();const text=$('todoText').value.trim(),value=$('todoRepo').value;if(!text)return;if(!value)return alert('Assegna la to do a un repo / sottoprogetto.');const [projectId,repoId]=value.split('|'),r=repoByIds(projectId,repoId);if(!r)return;const week=currentWeek();r.s.tasks.push({id:uid('t'),text,status:'todo',week,date:mondayFromWeek(week),hours:0,notes:'',reminder:false,completedAt:''});$('todoText').value='';await saveState(false);workspaceRender()};
$('addRepoQuick').onclick=()=>{const projects=(state.projects||[]).filter(p=>p.status!=='done');$('quickRepoProject').innerHTML=projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(selectedProject!=='all')$('quickRepoProject').value=selectedProject;$('quickRepoName').value='';$('quickRepoDialog').showModal();setTimeout(()=>$('quickRepoName').focus(),0)};
$('quickRepoSave').onclick=async()=>{const p=projectById($('quickRepoProject').value),name=$('quickRepoName').value.trim();if(!p||!name)return;if(!Array.isArray(p.subprojects))p.subprojects=[];p.subprojects.push({id:uid('sub'),name,status:'active',repoUrl:'',localPath:'',tasks:[]});selectedProject=p.id;$('quickRepoDialog').close();await saveState(false);renderProjectIndex();workspaceRender()};
const baseRender=render;render=function(){baseRender();workspaceRender()};document.addEventListener('click',e=>{if(e.target.closest('.project-index-card')&&!e.target.closest('.project-edit-pencil'))setTimeout(workspaceRender,0);if(e.target.closest('.category-dot'))setTimeout(workspaceRender,0)});setTimeout(workspaceRender,100);